"""Offline compatibility gate: run before merging a contract change or deploying."""

import ast
import mimetypes
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock
import warnings

import pytest


ROOT = Path(__file__).resolve().parents[1]
VISION = "backend/services/vision_analyzer.py"
API = "backend/main.py"
UI = "frontend/app.py"
EXPECTED_BANDS = ((4.0, "LOW"), (6.0, "MODERATE"), (8.0, "HIGH"))

# API-owned envelope, not generated by Gemini (TASK-026 documents this field).
REPORT_ENVELOPE = {
    "climate_source",
    # Application-owned alert-attempt provenance, waived because Gemini does not generate it.
    "alert_attempted",
    # Analyzer-owned per-field zone-identity provenance; supplied vs inferred.
    "identity_source",
    # API-owned imagery provenance: a caller upload vs imagery fetched from Google Maps.
    "image_source",
    # Google requires the Maps attribution watermark stay visible on fetched imagery.
    "attribution_required",
    # Persisted document id returned with the application report.
    "doc_id",
}
# Firestore-owned metadata, not Heat Analysis Result fields. No deleted fields waived.
STORAGE_ENVELOPE = {"created_at"}
# /api/scans is an HTTP envelope containing reports, not itself a report.
HTTP_ENVELOPE = {"scans"}
# Climate readings are a separate contract; never apply these exemptions to reports.
CLIMATE_KEYS = {"station_id", "observation_date", "max_temp_c", "avg_temp_c", "source"}


@pytest.fixture
def sources():
    # backend/test_*.py are ad-hoc manual smoke scripts, not application code, and are already
    # excluded from collection by testpaths. EPIC-008 retires them.
    paths = sorted(
        path for path in (ROOT / "backend").rglob("*.py") if not path.name.startswith("test_")
    ) + [ROOT / UI]
    return {path.relative_to(ROOT).as_posix(): path.read_text() for path in paths}


def tree(sources, path):
    module = ast.parse(sources[path], filename=path)
    module.contract_path = path
    return module


def require(condition, path, node, message):
    assert condition, f"{path}:{getattr(node, 'lineno', 1)}: {message}"


def named(tree_node, name):
    matches = [node for node in ast.walk(tree_node) if getattr(node, "name", None) == name]
    require(len(matches) == 1, tree_node.contract_path, tree_node, f"expected one contract helper named {name}")
    return matches[0]


def assignment(tree_node, name, value=None):
    matches = [node for node in ast.walk(tree_node) if isinstance(node, ast.Assign)
               and any(isinstance(target, ast.Name) and target.id == name for target in node.targets)
               and (value is None or ast.unparse(node.value) == value)]
    require(len(matches) == 1, tree_node.contract_path, tree_node, f"expected one contract assignment to {name}")
    return matches[0]


def dotted(node):
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{dotted(node.value)}.{node.attr}"
    return "<dynamic>"


def field_access(node):
    if isinstance(node, ast.Subscript):
        return node.value, node.slice
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
        if node.func.attr == "get" and node.args:
            return node.func.value, node.args[0]
    return None


def check_coroutines(sources):
    modules = {path: path.removeprefix("backend/").removesuffix(".py").replace("/", ".")
               for path in sources if path.startswith("backend/")}
    parsed = {path: tree(sources, path) for path in modules}
    definitions = {}

    def index(node, prefix):
        for child in ast.iter_child_nodes(node):
            qualified = prefix
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                qualified = f"{prefix}.{child.name}"
                definitions[child] = qualified
            index(child, qualified)

    for path, module in parsed.items():
        index(module, modules[path])
    asynchronous = {qualified for node, qualified in definitions.items()
                    if isinstance(node, ast.AsyncFunctionDef)}
    failures = []
    schedulers = {"asyncio.run", "asyncio.create_task", "asyncio.ensure_future"}
    wrappers = {"asyncio.gather", "asyncio.wait_for", "asyncio.shield", "asyncio.to_thread"}
    asynchronous |= wrappers

    def visit_scope(scope, bindings, path):
        bindings = bindings.copy()
        if isinstance(scope, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
            for argument in ast.walk(scope.args):
                if isinstance(argument, ast.arg):
                    bindings[argument.arg] = "<parameter>"

        def local_nodes(node):
            yield node
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                return
            for child in ast.iter_child_nodes(node):
                yield from local_nodes(child)

        nodes = [node for statement in scope.body for node in local_nodes(statement)]
        for node in nodes:
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                bindings[node.id] = "<assigned>"
        for node in nodes:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    bindings[alias.asname or alias.name.split(".")[0]] = alias.name if alias.asname else alias.name.split(".")[0]
            elif isinstance(node, ast.ImportFrom):
                package = node.module or ""
                if node.level:
                    parts = modules[path].split(".")[:-node.level]
                    package = ".".join(parts + ([package] if package else []))
                for alias in node.names:
                    bindings[alias.asname or alias.name] = f"{package}.{alias.name}"
            elif node in definitions:
                bindings[node.name] = definitions[node]

        def resolve(node):
            if isinstance(node, ast.Name):
                return bindings.get(node.id, node.id)
            if isinstance(node, ast.Attribute):
                return f"{resolve(node.value)}.{node.attr}"
            return "<dynamic>"

        for _ in range(3):
            for node in nodes:
                if isinstance(node, ast.Assign) and isinstance(node.value, (ast.Name, ast.Attribute)):
                    for target in node.targets:
                        if isinstance(target, ast.Name):
                            bindings[target.id] = resolve(node.value)
        parents = {child: parent for parent in ast.walk(scope) for child in ast.iter_child_nodes(parent)}

        def consumed(node):
            parent = parents.get(node)
            if isinstance(parent, ast.Await):
                return True
            if isinstance(parent, ast.Call) and node in parent.args:
                consumer = resolve(parent.func)
                return consumer in schedulers or consumer in wrappers - {"asyncio.to_thread"} and consumed(parent)
            if isinstance(parent, ast.Assign):
                targets = {target.id for target in parent.targets if isinstance(target, ast.Name)}
                uses = [candidate for candidate in nodes if isinstance(candidate, ast.Name)
                        and isinstance(candidate.ctx, ast.Load) and candidate.id in targets]
                return bool(uses) and all(consumed(use) for use in uses)
            return False

        for node in nodes:
            if not isinstance(node, ast.Call):
                continue
            if resolve(node.func) == "asyncio.to_thread" and node.args and resolve(node.args[0]) in asynchronous:
                failures.append(f"{path}:{node.lineno}: asyncio.to_thread does not await an async callable; schedule or await it instead")
            if resolve(node.func) not in asynchronous:
                if dotted(node.func).split(".")[-1] in {name.split(".")[-1] for name in asynchronous}:
                    warnings.warn(f"{path}:{node.lineno}: coroutine call resolution is uncertain: {dotted(node.func)}", stacklevel=2)
                continue
            if not consumed(node):
                failures.append(f"{path}:{node.lineno}: {dotted(node.func)} returns a coroutine; await it or pass it to an asyncio coroutine consumer")
        for node in nodes:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                visit_scope(node, bindings, path)

    for path, module in parsed.items():
        visit_scope(module, {}, path)
    assert not failures, "\n".join(failures)


def check_report_fields(sources):
    from services.vision_analyzer import HotspotAnalysisResult

    schema = HotspotAnalysisResult
    failures = []
    for path in sources:
        module = tree(sources, path)
        roots = {node.id: schema for node in ast.walk(module) if isinstance(node, ast.Name)
                 and ("report" in node.id or node.id in {"payload", "zone_data"}
                      or path == UI and node.id in {"data", "scan"}
                      or path == VISION and node.id == "result")}

        def model_for(node):
            if isinstance(node, ast.Name):
                return roots.get(node.id)
            if isinstance(node, ast.BoolOp):
                return model_for(node.values[0])
            access = field_access(node)
            if access:
                base, key = access
                model = model_for(base)
                if model and isinstance(key, ast.Constant) and key.value in model.model_fields:
                    annotation = model.model_fields[key.value].annotation
                    if hasattr(annotation, "model_fields"):
                        return annotation
            return None

        for _ in range(3):
            for node in ast.walk(module):
                if isinstance(node, ast.Assign):
                    model = model_for(node.value)
                    if model:
                        for target in node.targets:
                            if isinstance(target, ast.Name):
                                roots[target.id] = model
        for node in ast.walk(module):
            access = field_access(node)
            if not access:
                continue
            base, key = access
            model = model_for(base)
            if not model:
                allowed = None
                if isinstance(base, ast.Name) and base.id == "reading":
                    allowed = CLIMATE_KEYS
                elif path == UI and isinstance(base, ast.Call) and dotted(base.func) in {"response.json", "history_res.json"}:
                    allowed = HTTP_ENVELOPE
                if allowed is not None:
                    require(isinstance(key, ast.Constant) and key.value in allowed, path, node, "undefined non-report envelope key")
                continue
            allowed = set(model.model_fields)
            if model is schema:
                allowed |= REPORT_ENVELOPE | STORAGE_ENVELOPE
            if not isinstance(key, ast.Constant) or key.value not in allowed:
                failures.append(f"{path}:{node.lineno}: {ast.unparse(node)} reads/writes an undefined {model.__name__} field; schema fields: {sorted(allowed)}")
    assert not failures, "\n".join(failures)


def isolated_function(module, name, namespace, path):
    function = named(module, name)
    require(isinstance(function, ast.FunctionDef), path, function, f"{name} must remain synchronous")
    exec(compile(ast.Module(body=[function], type_ignores=[]), path, "exec"), namespace)
    return namespace[name], function


def check_risk_bands(sources):
    module = tree(sources, VISION)
    bands = assignment(module, "RISK_BANDS")
    require(ast.literal_eval(bands.value) == EXPECTED_BANDS, VISION, bands, "RISK_BANDS disagrees with COPILOT_GUIDE section 3")
    classifier, function = isolated_function(module, "risk_level_for_score", {"RISK_BANDS": EXPECTED_BANDS}, VISION)
    for score, expected in ((1.0, "LOW"), (3.999, "LOW"), (4.0, "MODERATE"),
                            (5.999, "MODERATE"), (6.0, "HIGH"), (7.999, "HIGH"),
                            (8.0, "CRITICAL"), (10.0, "CRITICAL")):
        require(classifier(score) == expected, VISION, function, f"HVI {score} must map to {expected}")
    for path in sources:
        current = tree(sources, path)
        score_names = {"hvi_score", "score", "hvi"}
        for node in ast.walk(current):
            if isinstance(node, ast.Assign) and "hvi_score" in ast.unparse(node.value):
                score_names.update(target.id for target in node.targets if isinstance(target, ast.Name))
        for node in ast.walk(current):
            if path == VISION and function.lineno <= getattr(node, "lineno", 0) <= function.end_lineno:
                continue
            if isinstance(node, ast.Compare):
                uses_score = any(isinstance(child, ast.Name) and child.id in score_names
                                 or isinstance(child, ast.Constant) and child.value == "hvi_score"
                                 for child in ast.walk(node))
                require(not uses_score, path, node, "HVI thresholds must be derived only by vision_analyzer.risk_level_for_score; consume risk_level instead")
            if isinstance(node, ast.Assign) and any(field_access(target) and ast.unparse(field_access(target)[1]) == "'risk_level'" for target in node.targets):
                require(path == VISION and isinstance(node.value, ast.Call) and dotted(node.value.func) == "risk_level_for_score", path, node, "risk_level must come from the analyzer's single classifier")


def check_image_mime(sources):
    api, ui, vision = (tree(sources, path) for path in (API, UI, VISION))
    allowed = assignment(api, "ALLOWED_UPLOAD_CONTENT_TYPES")
    accepted = ast.literal_eval(allowed.value)
    require(accepted == {"image/jpeg", "image/png"}, API, allowed, "API image allowlist must be exactly JPEG and PNG")
    mime = assignment(api, "mime_type")
    require(ast.unparse(mime.value) == "file.content_type", API, mime, "API must preserve the uploaded MIME type")
    guards = [node for node in ast.walk(api) if isinstance(node, ast.If)
              and ast.unparse(node.test) == "mime_type not in ALLOWED_UPLOAD_CONTENT_TYPES"]
    require(bool(guards) and "415" in ast.unparse(guards[0]), API, mime, "API must reject unsupported MIME with 415")
    calls = [node for node in ast.walk(api) if isinstance(node, ast.Call) and dotted(node.func) == "analyze_urban_hotspot"]
    require(bool(calls), API, mime, "API must call the analyzer")
    for call in calls:
        require(any(keyword.arg == "mime_type" and ast.unparse(keyword.value) == "mime_type" for keyword in call.keywords), API, call, "API must forward MIME to the analyzer")
    analyzer = named(vision, "analyze_urban_hotspot")
    require(any(argument.arg == "mime_type" for argument in analyzer.args.kwonlyargs), VISION, analyzer, "analyzer must accept mime_type")
    parts = [node for node in ast.walk(analyzer) if isinstance(node, ast.Call) and dotted(node.func) == "types.Part.from_bytes"]
    require(bool(parts), VISION, analyzer, "analyzer must construct an image part")
    for part in parts:
        require(any(keyword.arg == "mime_type" and ast.unparse(keyword.value) == "mime_type" for keyword in part.keywords), VISION, part, "Gemini image part must use forwarded MIME")
    uploader = next(node for node in ast.walk(ui) if isinstance(node, ast.Call) and dotted(node.func) == "st.file_uploader")
    extensions = ast.literal_eval(next(keyword.value for keyword in uploader.keywords if keyword.arg == "type"))
    content, files = assignment(ui, "content_type"), assignment(ui, "files")
    require("mimetypes.guess_type(uploaded_file.name)" in ast.unparse(content.value), UI, content, "dashboard MIME must be derived from the filename, never hardcoded")
    observed = set()
    for extension in extensions:
        upload = SimpleNamespace(name=f"aerial.{extension}", getvalue=lambda: b"offline-image")
        namespace = {"mimetypes": mimetypes, "uploaded_file": upload}
        exec(compile(ast.Module(body=[content, files], type_ignores=[]), UI, "exec"), namespace)
        sent = namespace["files"]["file"][2]
        expected = mimetypes.guess_type(upload.name)[0]
        require(sent == expected and sent in accepted, UI, files, f".{extension} sends {sent}; expected {expected}, API accepts {sorted(accepted)}")
        observed.add(sent)
    require(observed == accepted, UI, uploader, "dashboard extensions and API accepted MIME sets disagree")
    posts = [node for node in ast.walk(ui) if isinstance(node, ast.Call) and dotted(node.func) == "requests.post"]
    require(bool(posts) and all(any(keyword.arg == "files" and ast.unparse(keyword.value) == "files" for keyword in call.keywords) for call in posts), UI, files, "dashboard must send the verified multipart files")


def check_alert_provenance(sources):
    api, ui = tree(sources, API), tree(sources, UI)
    publisher = Mock()
    trigger, trigger_node = isolated_function(api, "trigger_alert_if_critical", {"dispatch_heat_alert": publisher}, API)
    streamlit = Mock()
    render, render_node = isolated_function(ui, "render_critical_alert", {"st": streamlit}, UI)
    for risk in ("LOW", "MODERATE", "HIGH", "CRITICAL"):
        for message_id in ("", "published-id"):
            publisher.reset_mock()
            publisher.return_value = message_id
            report = {"risk_level": risk, "hvi_score": 8.0 if risk == "CRITICAL" else 4.0, "alert_dispatched": True}
            trigger(report)
            expected = risk == "CRITICAL" and bool(message_id)
            require(report["alert_dispatched"] is expected, API, trigger_node, f"{risk}, publish result {message_id!r}: alert_dispatched must mean successful publish")
            require(publisher.call_count == int(risk == "CRITICAL"), API, trigger_node, "publish only when analyzer reports CRITICAL")
            streamlit.reset_mock()
            render(report)
            require(streamlit.error.call_count == int(expected), UI, render_node, "confirmed alert banner must depend on successful publish, not high HVI")
            require(streamlit.warning.call_count == int(risk == "CRITICAL" and not expected), UI, render_node, "critical unpublished report must display unconfirmed dispatch")
    for status in (False, None, "true", 1):
        streamlit.reset_mock()
        render({"risk_level": "CRITICAL", "alert_dispatched": status})
        require(not streamlit.error.called and streamlit.warning.called, UI, render_node, "only literal True confirms dispatch; missing or malformed status does not")
    dispatched = assignment(ui, "dispatched")
    status = assignment(ui, "dispatch_status", "'-'")
    status_checks = [node for node in ast.walk(ui) if isinstance(node, ast.If)
                     and ast.unparse(node.test) == "dispatched is True"]
    require(bool(status_checks), UI, dispatched, "history dispatch label must check literal True")
    for published in (True, False, None):
        namespace = {"scan": {"risk_level": "CRITICAL", "alert_dispatched": published}}
        exec(compile(ast.Module(body=[dispatched, status, status_checks[0]], type_ignores=[]), UI, "exec"), namespace)
        expected = "Confirmed" if published is True else "Not confirmed" if published is False else "-"
        require(namespace["dispatch_status"] == expected, UI, dispatched, "history must label publish status, not risk score")
    for path in (API, VISION):
        for node in ast.walk(tree(sources, path)):
            if isinstance(node, ast.Assign) and any(field_access(target) and ast.unparse(field_access(target)[1]) == "'alert_dispatched'" for target in node.targets):
                expected = ast.unparse(node.value) == "False" or path == API and ast.unparse(node.value) == "bool(dispatch_heat_alert(report))"
                require(expected, path, node, "alert_dispatched may only be reset False or derived from the publisher's message ID")
    route = named(api, "analyze_hotspot")
    dispatch_calls = [node for node in ast.walk(route) if isinstance(node, ast.Call) and dotted(node.func) == "asyncio.to_thread" and node.args and dotted(node.args[0]) == "trigger_alert_if_critical"]
    saves = [node for node in ast.walk(route) if isinstance(node, ast.Call) and dotted(node.func) == "asyncio.to_thread" and node.args and dotted(node.args[0]) == "save_hotspot_report"]
    require(bool(dispatch_calls) and bool(saves) and dispatch_calls[0].lineno < saves[0].lineno and ast.unparse(dispatch_calls[0].args[1]) == ast.unparse(saves[0].args[1]), API, route, "persist the same report only after resolving alert provenance")
    parents = {child: parent for parent in ast.walk(route) for child in ast.iter_child_nodes(parent)}
    for call in dispatch_calls + saves:
        require(isinstance(parents[call], ast.Await), API, call, "dispatch and persistence must be awaited in order")


def rejected_mutation(sources, path, old, new, checker, bug):
    require(sources[path].count(old) == 1, path, ast.parse("pass").body[0], "negative fixture anchor must occur exactly once")
    mutated = dict(sources, **{path: sources[path].replace(old, new)})
    with pytest.raises(AssertionError) as failure:
        checker(mutated)
    assert f"{path}:" in str(failure.value), "rejection must identify the offending file and line"
    print(f"\n{bug} REJECTED\n{failure.value}")


def test_every_resolved_backend_coroutine_call_is_consumed(sources):
    check_coroutines(sources)


def test_all_report_field_reads_match_the_producer_schema(sources):
    check_report_fields(sources)


def test_report_envelope_matches_application_model_and_canonical_validator():
    import runpy

    import main
    from services.vision_analyzer import HotspotAnalysisResult

    application_fields = set(main.AnalysisResponse.model_fields) - set(HotspotAnalysisResult.model_fields)
    validator_path = ROOT / ".github/skills/heat-report-validation/scripts/validate_report.py"
    validator = runpy.run_path(str(validator_path))
    assert application_fields == REPORT_ENVELOPE
    assert application_fields == validator["REPORT_ENVELOPE_FIELDS"]
    assert application_fields == set(validator["REPORT_ENVELOPE_SCHEMA"])


def test_hvi_bands_have_one_classifier_and_match_spec_boundaries(sources):
    check_risk_bands(sources)


def test_dashboard_api_and_analyzer_preserve_image_mime(sources):
    check_image_mime(sources)


def test_alert_flag_and_banner_mean_successful_publish_before_persistence(sources):
    check_alert_provenance(sources)


def test_historical_bug_007_unawaited_analyzer_is_rejected(sources):
    rejected_mutation(sources, API, "analysis_report = await analyze_urban_hotspot(", "analysis_report = analyze_urban_hotspot(", check_coroutines, "BUG-007")


def test_historical_bug_008_deleted_emergency_field_is_rejected(sources):
    rejected_mutation(sources, API, 'report.get("risk_level") == "CRITICAL"', 'report.get("requires_emergency_alert")', check_report_fields, "BUG-008")


def test_historical_bug_012_deleted_dashboard_temperature_is_rejected(sources):
    rejected_mutation(sources, UI, 'data.get("ambient_temp_c")', 'data.get("surface_temp_estimate_c")', check_report_fields, "BUG-012")
    rejected_mutation(sources, UI, 'report.get("alert_dispatched") is True', 'report.get("requires_emergency_alert")', check_report_fields, "BUG-012 banner")


def test_historical_bug_018_png_mislabeled_as_jpeg_is_rejected(sources):
    rejected_mutation(sources, UI, "mimetypes.guess_type(uploaded_file.name)[0] or JPEG_MIME_TYPE", '"image/jpeg"', check_image_mime, "BUG-018")


@pytest.mark.parametrize("call", ["await infer()", "aio.run(infer())", "aio.create_task(infer())",
                                 "await aio.gather(infer())", "pending = infer(); await pending",
                                 "await aio.to_thread(lambda: aio.run(infer()))"])
def test_coroutine_gate_accepts_import_aliases_and_deliberate_consumers(call):
    check_coroutines({"backend/producer.py": "async def analyze(): pass",
                      "backend/consumer.py": f"import asyncio as aio\nfrom producer import analyze as infer\nasync def route():\n    {call}\n"})


@pytest.mark.parametrize("call", ["infer()", "aio.gather(infer())", "await aio.to_thread(infer)",
                                 "await aio.to_thread(infer())"])
def test_coroutine_gate_rejects_discarded_or_threaded_coroutines(call):
    with pytest.raises(AssertionError, match="backend/consumer.py:4:"):
        check_coroutines({"backend/producer.py": "async def analyze(): pass",
                          "backend/consumer.py": f"import asyncio as aio\nfrom producer import analyze as infer\nasync def route():\n    {call}\n"})


def test_coroutine_gate_resolves_nested_async_definitions():
    with pytest.raises(AssertionError, match="backend/nested.py:3:"):
        check_coroutines({"backend/nested.py": "def factory():\n    async def analyze(): pass\n    analyze()\n"})


def test_coroutine_gate_reports_uncertain_parameter_shadowing():
    with pytest.warns(UserWarning, match="resolution is uncertain"):
        check_coroutines({"backend/shadow.py": "async def analyze(): pass\ndef consumer(analyze):\n    analyze()\n"})


def test_report_gate_rejects_deleted_nested_fields_and_aliases():
    with pytest.raises(AssertionError, match="frontend/app.py:3:"):
        check_report_fields({UI: 'alias = data\nplan = alias.get("passive_cooling_plan") or {}\nplan["surface_temp_estimate_c"]\n'})


def test_hvi_gate_rejects_dashboard_threshold_rederivation(sources):
    mutated = dict(sources, **{UI: sources[UI] + '\nif data["hvi_score"] >= 8.0:\n    pass\n'})
    with pytest.raises(AssertionError, match="frontend/app.py:.*HVI thresholds"):
        check_risk_bands(mutated)


def test_hvi_gate_rejects_drifted_analyzer_boundaries(sources):
    rejected_mutation(sources, VISION, '((4.0, "LOW"), (6.0, "MODERATE"), (8.0, "HIGH"))', '((4.0, "LOW"), (6.0, "MODERATE"), (8.1, "HIGH"))', check_risk_bands, "HVI boundary drift")


def test_mime_gate_rejects_api_dropping_forwarded_mime(sources):
    rejected_mutation(sources, API, "mime_type=mime_type,", 'mime_type="image/jpeg",', check_image_mime, "API MIME drift")


def test_alert_gate_rejects_claiming_dispatch_on_publish_failure(sources):
    rejected_mutation(sources, API, 'bool(dispatch_heat_alert(report))', 'True', check_alert_provenance, "Publish provenance drift")


def test_alert_gate_rejects_dashboard_claiming_dispatch_from_risk_alone(sources):
    rejected_mutation(sources, UI, 'report.get("alert_dispatched") is True', 'True', check_alert_provenance, "Banner provenance drift")


def test_alert_gate_rejects_history_claiming_dispatch_from_risk_alone(sources):
    rejected_mutation(sources, UI, 'dispatched = scan.get("alert_dispatched")', 'dispatched = scan.get("risk_level") == "CRITICAL"', check_alert_provenance, "History provenance drift")


def test_alert_gate_rejects_persistence_before_dispatch_completion(sources):
    rejected_mutation(sources, API, "await asyncio.to_thread(trigger_alert_if_critical, analysis_report)", "asyncio.to_thread(trigger_alert_if_critical, analysis_report)", check_alert_provenance, "Persistence ordering drift")